import { randomUUID } from 'node:crypto';
import { config } from '../config.js';
import { getSupabaseAdmin, isSupabaseConfigured } from '../lib/supabase.js';
import { ApiError } from '../utils/http.js';

/**
 * Product image storage helpers.
 *
 * Uploads always happen in the backend with the server-only Supabase client.
 * The browser sends multipart file bytes, never a storage URL or an arbitrary
 * object path. In the normal no-Supabase development mode we use a data URL so
 * the same product flow can still be exercised locally and in tests.
 */

const EXTENSION_BY_MIME = {
  'image/png': '.png',
  'image/jpeg': '.jpg',
  'image/webp': '.webp',
  'image/avif': '.avif',
  'image/gif': '.gif'
};

function storageIsAvailable() {
  return config.useSupabase && isSupabaseConfigured;
}

function safePathSegment(value) {
  return String(value || 'unassigned').replace(/[^a-zA-Z0-9_-]/g, '_');
}

function isManagedObjectPath(path) {
  return /^(?:sellers|admins)\/[a-zA-Z0-9_-]+\/[0-9a-f-]{36}\.(?:png|jpg|webp|avif|gif)$/i.test(
    path
  );
}

function imageObjectPath(file, { sellerId, userId } = {}) {
  const owner = sellerId ? `sellers/${safePathSegment(sellerId)}` : `admins/${safePathSegment(userId)}`;
  const extension = EXTENSION_BY_MIME[file.mimetype] || '.bin';
  return `${owner}/${randomUUID()}${extension}`;
}

/**
 * Upload one or more multer memory-storage files.
 *
 * @param {Array<{buffer: Buffer, mimetype: string, originalname?: string}>} files
 * @param {{sellerId?: string|null, userId?: string|null}} owner
 * @returns {Promise<Array<{url: string, path: string}>>}
 */
export async function uploadProductImages(files, owner = {}) {
  const selected = Array.isArray(files) ? files.filter(Boolean) : [];
  if (selected.length > config.productImages.maxFiles) {
    throw ApiError.unprocessable('Too many product images', {
      images: `Upload at most ${config.productImages.maxFiles} images`
    });
  }

  const uploaded = [];
  try {
    for (const file of selected) {
      if (!Buffer.isBuffer(file.buffer) || file.buffer.length === 0) {
        throw ApiError.unprocessable('Invalid product image', {
          images: 'Each image must contain file data'
        });
      }
      if (!config.productImages.allowedMimeTypes.includes(file.mimetype)) {
        throw ApiError.unprocessable('Unsupported product image type', {
          images: `Allowed image types: ${config.productImages.allowedMimeTypes.join(', ')}`
        });
      }

      const path = imageObjectPath(file, owner);

      if (!storageIsAvailable()) {
        // Memory mode is intentionally self-contained: this gives the UI a
        // usable image without pretending that a local file was persisted to
        // a cloud bucket.
        uploaded.push({
          path,
          url: `data:${file.mimetype};base64,${file.buffer.toString('base64')}`
        });
        continue;
      }

      const bucket = getSupabaseAdmin().storage.from(config.productImages.bucket);
      const { error } = await bucket.upload(path, file.buffer, {
        contentType: file.mimetype,
        cacheControl: '3600',
        upsert: false
      });
      if (error) {
        console.error('[storage] product image upload failed:', error);
        throw new ApiError(502, 'Could not store product image');
      }

      // Track the object before asking for its public URL so a URL-generation
      // failure is compensated by the catch block below.
      const record = { path, url: '' };
      uploaded.push(record);
      const { data } = bucket.getPublicUrl(path);
      if (!data?.publicUrl) {
        throw new ApiError(502, 'Could not create product image URL');
      }
      record.url = data.publicUrl;
    }

    return uploaded;
  } catch (error) {
    // Do not leave earlier files behind when a later file fails.
    await removeProductImageUploads(uploaded).catch((cleanupError) => {
      console.error('[storage] product image cleanup failed:', cleanupError);
    });
    throw error;
  }
}

/**
 * Extract an object path from a public URL generated by Supabase. Seeded and
 * externally hosted image URLs return null and are never deleted.
 */
export function productImagePathFromUrl(url) {
  if (typeof url !== 'string' || !config.supabase.url) return null;

  let parsed;
  let configured;
  try {
    parsed = new URL(url);
    configured = new URL(config.supabase.url);
  } catch {
    return null;
  }
  if (parsed.origin !== configured.origin) return null;

  const prefix = `/storage/v1/object/public/${config.productImages.bucket}/`;
  if (!parsed.pathname.startsWith(prefix)) return null;

  let decoded;
  try {
    decoded = decodeURIComponent(parsed.pathname.slice(prefix.length));
  } catch {
    return null;
  }
  // Only remove objects created by this service's server-controlled prefixes;
  // never delete an arbitrary object merely because its URL contains the
  // bucket name.
  return isManagedObjectPath(decoded) ? decoded : null;
}

/** Delete uploaded objects by their returned paths. */
export async function removeProductImageUploads(uploads) {
  const paths = (Array.isArray(uploads) ? uploads : [])
    .map((upload) => upload?.path)
    .filter(isManagedObjectPath);
  if (!storageIsAvailable() || paths.length === 0) return;

  const { error } = await getSupabaseAdmin()
    .storage.from(config.productImages.bucket)
    .remove(paths);
  if (error) throw new ApiError(502, 'Could not remove product image');
}

/** Delete only images that belong to this application's public bucket. */
export async function removeProductImageUrls(urls) {
  const paths = (Array.isArray(urls) ? urls : [])
    .map(productImagePathFromUrl)
    .filter(Boolean);
  if (!storageIsAvailable() || paths.length === 0) return;

  const { error } = await getSupabaseAdmin()
    .storage.from(config.productImages.bucket)
    .remove(paths);
  if (error) throw new ApiError(502, 'Could not remove product image');
}
