-- SpaceFit initial schema
-- Tables: profiles, categories, products, product_images, carts, cart_items,
--         orders, order_items, consultations, newsletter_subscribers
-- All tables live in the `public` schema and use RLS.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- profiles
-- Application profile data, one row per auth user.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  avatar_path text,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -------------------------------------------------------------- categories
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- products
create table if not exists public.products (
  id text primary key,
  title text not null,
  slug text not null unique,
  category_id bigint references public.categories(id) on delete set null,
  price numeric(14, 2) not null check (price >= 0),
  orig_price numeric(14, 2) check (orig_price is null or orig_price >= 0),
  currency text not null default 'NGN',
  rating numeric(3, 2) not null default 0 check (rating >= 0 and rating <= 5),
  reviews integer not null default 0 check (reviews >= 0),
  availability text not null default 'In stock',
  short_description text,
  description text,
  features jsonb not null default '[]'::jsonb,
  specs jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_featured_idx on public.products(featured) where featured = true;
create index if not exists products_price_idx on public.products(price);

-- ---------------------------------------------------------- product_images
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  url text not null,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists product_images_product_idx on public.product_images(product_id, position);

-- ------------------------------------------------------------------ carts
create table if not exists public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists carts_user_idx on public.carts(user_id);

-- ------------------------------------------------------------- cart_items
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id uuid not null references public.carts(id) on delete cascade,
  product_id text not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  size text,
  color text,
  created_at timestamptz not null default now()
);

-- Prevent duplicate identical line items within a cart.
create unique index if not exists cart_items_unique_line
  on public.cart_items (cart_id, product_id, coalesce(size, ''), coalesce(color, ''));

create index if not exists cart_items_cart_idx on public.cart_items(cart_id);

-- ----------------------------------------------------------------- orders
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled')),
  currency text not null default 'NGN',
  subtotal numeric(14, 2) not null check (subtotal >= 0),
  delivery_fee numeric(14, 2) not null default 0 check (delivery_fee >= 0),
  vat numeric(14, 2) not null default 0 check (vat >= 0),
  total numeric(14, 2) not null check (total >= 0),
  customer jsonb not null,
  delivery jsonb not null,
  payment_method text not null check (payment_method in ('card', 'transfer', 'cash')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_created_idx on public.orders(created_at desc);

-- ------------------------------------------------------------ order_items
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null references public.products(id) on delete restrict,
  name text not null,
  price numeric(14, 2) not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  size text,
  color text,
  created_at timestamptz not null default now()
);

create index if not exists order_items_order_idx on public.order_items(order_id);

-- --------------------------------------------------------- consultations
create table if not exists public.consultations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  email text not null,
  phone text not null,
  city text not null,
  room_type text,
  preferred_date date,
  notes text,
  status text not null default 'requested'
    check (status in ('requested', 'scheduled', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists consultations_email_idx on public.consultations(email);

-- ---------------------------------------------------- newsletter_subscribers
create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------- updated_at trigger
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_updated_at_profiles on public.profiles;
create trigger set_updated_at_profiles
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_products on public.products;
create trigger set_updated_at_products
  before update on public.products
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_carts on public.carts;
create trigger set_updated_at_carts
  before update on public.carts
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_orders on public.orders;
create trigger set_updated_at_orders
  before update on public.orders
  for each row execute function public.set_updated_at();

-- ---------------------------------------- auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'first_name'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
